name: PHP_New_test

on:
  workflow_dispatch:

jobs:
  PHP_New_test:
    runs-on: Ubuntu-latest  
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '8'
        
